### ISSUE TITLE
Settings persistence

### ISSUE THREAD

**Issue by zspitz** [zspitz/ANTLR4ParseTreeVisualizer#18]
Store JSON in %ProgramData%.

File should be read when visualizer is first started.

File should be written at two points:

1. after TransferObject returns (as the debuggee might have changed settings)
2. after PropertyChanged is triggered on settings object

How can we persist parser specific settings? If we have a single settings file, we'll have to find some way of merging settings from multiple parser/lexer classes into a single object.

Alternatively, we could store each lexer / parser settings in its own file. We'd need some sort of naming scheme, as we couldn't use `\` from the path as the file name.

We could simply use numbers and store the corresponding assembly / classname in the global settings file.

**Comment by bclothier** [comment]
You might want to consider that such setting might be project-specific (or more likely, solution-specific). Can you use `.suo` file for that purpose?

**Comment by zspitz** [comment]
@bclothier I don't think so. The visualizer is purely a runtime DLL, parts of which are injected into the debugged DLL. There may not always be a loaded project.

But I'm thinking to make it assembly-specific; IOW, every time a given assembly (either the executing assembly, or the current assembly) is debugged, it will use the same selected parser as last time.

**Comment by zspitz** [comment]
There's another wrinkle here. The visualizer DLL is loaded in two places: in Visual Studio, and in the debugged assembly; both halves communicate using serialized data. But the Visual Studio side has no knowledge of which DLLs are loaded; we have to make a special request to the debuggee side.

**Comment by zspitz** [comment]
And the only DLL which has any meaning in this context is the assembly of the visualizer target type (Assembly.GetAssembly). For the purposes of this visualizer, that's enough. I tried these others, and they all returned either the Microsoft visualizer base DLL, or `null` (I don't recall).

- Assembly.CallingAssembly
- Assembly.GetEntryAssembly
- Assembly.GetExecutingAssembly

**Comment by zspitz** [comment]
It should be noted that reading the type of the object targeted by the visualizer, is only useful for the ANTLR visualizer; it doesn't say which assembly is currently being debugged.
