### ISSUE TITLE
Show build/version number somewhere

### ISSUE THREAD

**Issue by retailcoder** [zspitz/ANTLR4ParseTreeVisualizer#28]
It would be useful to show the version number somewhere on the settings panel:

![settings panel with red arrow pointing to the bottom-left](https://user-images.githubusercontent.com/5751684/65380225-968bc380-dca4-11e9-84d5-a5da7e9d6eab.png)

A smaller font, grey brush perhaps.

**Comment by zspitz** [comment]
@retailcoder How's this:

![image](https://user-images.githubusercontent.com/312166/65393801-4ee16680-dd8e-11e9-9a50-24ff59ad6a61.png)
