### ISSUE TITLE
Token list should show more than just IDs

### ISSUE THREAD

**Issue by retailcoder** [zspitz/ANTLR4ParseTreeVisualizer#29]
The list of tokens should include the token names:

!["Filter token types" list showing a list of numbers](https://user-images.githubusercontent.com/5751684/65380210-69d7ac00-dca4-11e9-9f8f-f21ebf9b6aaf.png)

In a grey brush font, maybe (like the "(Type)" under the "Filter rule contexts" box).

**Comment by zspitz** [comment]
As part of https://github.com/zspitz/ANTLR4ParseTreeVisualizer/commit/885074341494c63599ed90ee08fb689cc7f02876, this shouldn't happen, because the correct parser class should load automatically.

**Comment by zspitz** [comment]
The ID should still be shown.

**Comment by retailcoder** [comment]
Nice!

![with VBAParser loaded, list shows only token names](https://user-images.githubusercontent.com/5751684/65380257-5547e380-dca5-11e9-8199-9087b2b1e7e8.png)

It would be nice to have both the names and their respective ID though.. but then I'd show the ID in greyed-out parentheses.

**Comment by zspitz** [comment]
Token type ID and rule ID now show in gray parentheses.

**Comment by zspitz** [comment]
@retailcoder are you getting notifications for this?

![image](https://user-images.githubusercontent.com/312166/65386086-b45a3680-dd3f-11e9-9e7e-1f8dfe909850.png)

**Comment by retailcoder** [comment]
Yup, my phone was dead though =)
That's awesome, well done!
