### ISSUE TITLE
Source box selection doesn't keep up

### ISSUE THREAD

**Issue by retailcoder** [zspitz/ANTLR4ParseTreeVisualizer#30]
![selection not syncing in "source" box](https://i.stack.imgur.com/0UPv8.gif)

**Comment by zspitz** [comment]
I think I know what's happening here. I've always opened the visualizer against the root node of a parse tree; thus the character span for each node begins at 0. That's not a justified assumption, as in this case. I'm guessing you opened the visualizer on a child node of the parse tree, so the character span begins at 82, but the text selection has to start from 0.

**Comment by zspitz** [comment]
@retailcoder Can you verify that this is resolved in https://github.com/zspitz/ANTLR4ParseTreeVisualizer/releases/tag/0.0.0.26?

**Comment by zspitz** [comment]
@retailcoder Have you had a chance to check this?
