### ISSUE TITLE
The visualizer tool doesn't work - VS 2017 Enterprise

### ISSUE THREAD

**Issue by BrunoParrotta** [zspitz/ANTLR4ParseTreeVisualizer#51]
The error is 
"Impossibile caricare il tipo 'System.ValueTuple`2' dall'assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'."
- Stack trace:

 at ParseTreeVisualizer.VisualizerData..ctor(Object o, Config config) in C:\projects\antlr4parsetreevisualizer\Shared\Models\VisualizerData.cs:line 192
   at ParseTreeVisualizer.ObjectSource.TransferData(Object target, Stream incomingData, Stream outgoingData) in C:\projects\antlr4parsetreevisualizer\Shared\VisualizerDataObjectSource.cs:line 10
   at Microsoft.VisualStudio.DebuggerVisualizers.ClrCustomVisualizers.ClrCustomVisualizerDebuggeeHost.TransferData(Object visualizedObject, Byte[] uiSideData)

Visual studio 2017 Enterprise - Version 15.9.17
.Net Framework 4.6.01055
AntlrRuntime DLL: version 4.6.5

**Comment by zspitz** [comment]
As an immediate workaround, you could download the [NuGet ValueTuple package](https://www.nuget.org/packages/System.ValueTuple/) and extract the dlls into the visualizer folder.

I'll look into a more permanent solution.

**Comment by zspitz** [comment]
@BrunoParrotta I'm guessing this is because you're targeting .NET Framework 4.7.2, and value tuples were only introduced in 4.7.

If you open the NuGet package with an archiver, you want `lib\net461\System.ValueTuple.dll`.

**Comment by BrunoParrotta** [comment]
Thank for your answer, but i put 
System.ValueTuple.Dll  got from system.valuetuple.4.5.0.nupkg
in the same directory of Antlr4.Runtime.ParseTreeVisualizer
but it doesn't work.... :_-(

Stack trace is the same.

**Comment by zspitz** [comment]
@BrunoParrotta Your project is targeting .NET Framework 4.6.0, which only supports .NET Standard 1.0. Perhaps try the version in `lib\netstandard1.0\`?

I apologize for trying to find these hacky workarounds; I don't have the time right now to give this issue the attention it deserves. Perhaps in a few days.

**Comment by BrunoParrotta** [comment]
@zspitz Thank you for your support, but it doesnt' work...
Any other ideas?

**Comment by BrunoParrotta** [comment]
Solved after download of framework .net472, because it wasn't installed on my pc.
I thought it was....
this is the link. https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net472-web-installer

After solved this my little trouble i can say that tis is a great tool! 
Congratulations for the work done!

**Comment by zspitz** [comment]
That's great to hear, and I'm sorry I wasn't able to give this the attention it deserved.

Just to confirm: your project is still targeting 4.6.0?
