### ISSUE TITLE
Dialog size too large

### ISSUE THREAD

**Issue by doggy8088** [zspitz/ANTLR4ParseTreeVisualizer#53]
If my text big enough, I will not able to see full dialog of this tool.

![image](https://user-images.githubusercontent.com/88981/124409593-2ff17000-dd7b-11eb-8c88-b2ce03a6d485.png)

If I drag the window size large than one monitor width, then I can see "Properties" pane.

![image](https://user-images.githubusercontent.com/88981/124409381-c6716180-dd7a-11eb-9830-4b1c66f5ad35.png)

Can you fix the problem? Thanks.

**Comment by zspitz** [comment]
I've uploaded a new release; it should fix the issue. Please try and let me know.

**Comment by doggy8088** [comment]
@zspitz I tried. It's perfect. Thanks. 👍
